{"name": "test_login_succeed", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' in {'code': 1, 'message': '贺喜你，登录成功'}", "trace": "self = <case.test_login.test_login_one.TestLogin object at 0x000002B4CA7B68C8>\n\n    @pytest.mark.testmark\n    def test_login_succeed(self):\n        res = Login(username=TestLogin().test_get_csv_data()[1][0], password=TestLogin().test_get_csv_data()[1][1]).login()\n>       assert TestLogin().test_get_csv_data()[1][2] in res\nE       AssertionError: assert '1' in {'code': 1, 'message': '贺喜你，登录成功'}\n\ntest_login_one.py:36: AssertionError"}, "attachments": [{"name": "stdout", "source": "4e6c83a8-9225-4d63-82a1-f3bc6398b82f-attachment.txt", "type": "text/plain"}], "start": 1633701047471, "stop": 1633701047494, "uuid": "1b03afdd-8cc5-4693-bd76-e8f73dea6203", "historyId": "8acc0a1cf70cf2dbe369f345a62355e2", "testCaseId": "0a7f8b3b5ac1e4c2c2d0b7a5ab437480", "fullName": "case.test_login.test_login_one.TestLogin#test_login_succeed", "labels": [{"name": "tag", "value": "testmark"}, {"name": "parentSuite", "value": "case.test_login"}, {"name": "suite", "value": "test_login_one"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-JBQBBC5"}, {"name": "thread", "value": "16348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_login.test_login_one"}]}